### ISSUE TITLE
[Feature] make global settings optimal and set for all titles 

### ISSUE THREAD

**Issue by t0mtaylor** [DaedalusX64/daedalus#1]
Great work on Daedalus!

Can i propose a new feature:

- make global settings optimal like here set for all titles https://github.com/z2442/daedalus/wiki/Optimal-Settings

- titles can be changed independently as they can currently

This will make common settings be the default across all titles, and i only have to disable them per game if they cause an issue - should be able to change the default setting also

**Comment by wally4000** [comment]
Texture Update Check will be enabled as default for every frame eventually, the rest are too finicky to implement.

I've added the options to my list of things to review.
Thanks
