### ISSUE TITLE
Ukrainian translation issues

### ISSUE THREAD

**Issue by PhantomHorror** [DaedalusX64/daedalus#13]
Some issues regarding the Ukrainian translation:
1. There isn't a hash in it, because there isn't hash.txt in Default.7z (I marked that line with question marks).
2. For some reason some of the lines are displayed in English, although I translated them all into Ukrainian.
3. Some of the lines are displayed buggy, even though all Ukrainian symbols are supported.

**Comment by wally4000** [comment]
Hey, 

Apologies for not getting back to you sooner, we'll be unfortunately deprecating the Language Translation feature as the UI will be changing at some point in the near future. You would be more than welcome to contribute to Ukrainian Language translations when that time comes.

Please do stay safe and vigilant :)
