### ISSUE TITLE
Linux build doesn't work

### ISSUE THREAD

**Issue by stkruse** [DaedalusX64/daedalus#15]
When I try to run the linux build with
`./build_daedalus.sh LINUX_RELEASE`

I get the following error:
```
./daedalus/Source/BuildOptions.h:22:10: fatal error: Platform.h: fatal error no such file or directory
 #include "Platform.h"

```

**Comment by bombonatti** [comment]
Have you installed psptoolchain?
https://github.com/pspdev/psptoolchain

I have just downloaded/compiled it from scratch.

**Comment by wally4000** [comment]
Linux build has been fixed in a later commit :)
