### ISSUE TITLE
[BUG] Can't Save in Super Smash Bros

### ISSUE THREAD

**Issue by justwantNESS** [DaedalusX64/daedalus#21]
While other games work just fine, Super Smash Bros will not save.

Press HOME, Go to Save State, Select an Empty Slot, press X. 

In this case, the screen will go black and say "Saving..." for about half a second then return to the game, and when you go back to load the save state, it is not there, as if it never happened. In the games that work, the "Saving..." screen takes much longer to pass and the save state is readily accessible. 

I even tried making another folder, mso:/n64/SaveStates, which worked for other games but not for Super Smash Bros. 

Device:
 - Device: PSP 2001
 - FW: 6.60
 - Daedalus Version 1.1.8

Updated Daedalus, tried a different Super Smash Bros ROM, tried making a new directory for save states, and scoured the internet looking for a solution. I JUST WANT NESS!! (without having to unlock him every time)

THANKS

**Comment by justwantNESS** [comment]
Anybody home? What's the deal here, afraid to admit you haven't a clue? Well I hope you're workin on it, cuz I JUST WANT NESS. Someone out there must have what it takes to solve this issue!

**Comment by justwantNESS** [comment]
Has anyone else run into this problem? Cuz I...JUST...Want...NESS!! Can I get a woot woot? Ya feel me?

**Comment by ChrisDG776** [comment]
I'm sorry to hear this is happening to you , i my self am having issues with deadulus 1.1.8 . so what recommend you to do is download 1.1.7 and see if it works and also rinnegatamante doesn't care about the psp version anymore and is working on the vita version. also for your efforts i give you a whoot whoot. good luck!

**Comment by justwantNESS** [comment]
Haha, brilliant! Thanks for the advice, fellow traveler. I guess the PSP is getting lost in retro-land by now! All the better for those who can't let it go! I'll never put away my love for having an OG PSP in my hands, so I guess I gotta go into software-land and keep learning and trying out different things! I'll get back to this topic with my progress, cuz I JUST WANT NE555!!!

**Comment by ChrisDG776** [comment]
yeah i feel for you bud. but the psp will always have importance to me no matter what. and i'm glad i could be of assistance!

**Comment by justwantNESS** [comment]
I found something clever on the net...it's called Smash Remix...Consider this problem solved!

**Comment by CGG776** [comment]
well glad it worked, by the way have fun
