### ISSUE TITLE
Menu Text is broken when it is running on PS2 Software Emulator for PS3

### ISSUE THREAD

**Issue by RetroFan90** [DaedalusX64/daedalus#22]
When Running DaedalusX64-PS@ on PS3, The Text Is Just White Square Boxes.
[https://images-ext-2.discordapp.net/external/DfFSsVocjZV-rMwOy0IUOQx0_I8OpB7igOQ8uDH6WyU/%3Fwidth%3D952%26height%3D714/https/media.discordapp.net/attachments/574192318114955271/736223039330451597/JPEG_20200724_110638.jpg?width=820&height=615](url)

**Comment by Invictaz** [comment]
@RetroFan90 

Well @masterfeizz is looking into natively building Daedalus for PS3 with RSX dynarec

**Comment by Invictaz** [comment]
@RetroFan90 did you try the fork from @belek666 ?

**Comment by RetroFan90** [comment]
i used the fork from @uyjulian

**Comment by wally4000** [comment]
Please take this up with the other developers, this is for PSP / macOS / Linux Ports.
