### ISSUE TITLE
[BUG]Japanese is not displayed in menu

### ISSUE THREAD

**Issue by pspkurara** [DaedalusX64/daedalus#23]
Describe the bug
I created and tested Japanese lng on my own
Nonetheless I didn't see any characters (though it seemed to be using the system font)
Half-width alphanumeric characters are visible
I would like to add a Japanese translation, so please support.

To Reproduce
1. Add some Japanese language (double-byte character, not Unicode) to lng
2. Save as Japanese.lng
3. Start Daedaulus
4. Switch to Japanese with Language
5. Translated characters are not displayed

Expected behavior
Japanese written in lng is displayed correctly

Device:
 - Device: PSP-2000
 - FW: 6.60ME-1.8
 - Daedalus Version 1.1.8

Additional context
The character code of Japanese.lng was UTF-8 BOM

THANKYOU

**Comment by wally4000** [comment]
Thank you for logging this ticket,

Unfortunately as we're going to likely be reworking the User Interface we will be removing existing translations in favour of English for now .

I would encourage people when the time comes to provide translation data again if possible.

Thanks

**Comment by pspkurara** [comment]
Thank you for your reply
Hope it works
After being recreated, I hope that it will support double-byte characters at the same time (if it does, you will be able to create it yourself).
