### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Andoresan** [DaedalusX64/daedalus#24]
O emulador não reconhece meu save de Mario 64, a antiga versão reconhecia o save, a nova não mostra meu save, e não estou usando savestate, utilizo o save do jogo, eu exportei ele do meu antigo emulador e agora ele não aparece, meu psp é o modelo 2000.
The emulator doesn't recognize my Mario 64 save, the old version recognized the save, the new one doesn't show my save, and I'm not using savestate, I use the game's save, I exported it from my old emulator and now it doesn't show up, my psp is the 2000 model.

**Comment by wally4000** [comment]
Can you please share the file with us? The save format changed a bit in the early years I believe
