### ISSUE TITLE
[BUG] Can't build on a Mac 

### ISSUE THREAD

**Issue by spotanjo3** [DaedalusX64/daedalus#27]
Removing previous build attempt
rm: /Users/username/downloads/daedalus/DaedalusX64/EBOOT.PBP: No such file or directory
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release Build
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/downloads/daedalus/MACbuild
Scanning dependencies of target sysGL
[  2%] Building CXX object CMakeFiles/sysGL.dir/SysGL/Graphics/GraphicsContextGL.cpp.o
[  2%] Building CXX object CMakeFiles/sysGL.dir/SysGL/Graphics/NativeTextureGL.cpp.o
[  4%] Building CXX object CMakeFiles/sysGL.dir/SysGL/HLEGraphics/RendererGL.cpp.o
[  4%] Building CXX object CMakeFiles/sysGL.dir/SysGL/HLEGraphics/GraphicsPluginGL.cpp.o
[  5%] Building CXX object CMakeFiles/sysGL.dir/SysGL/Input/InputManagerGL.cpp.o
[  6%] Building CXX object CMakeFiles/sysGL.dir/SysGL/Interface/UI.cpp.o
/Users/username/downloads/daedalus/Source/SysGL/Graphics/NativeTextureGL.cpp:29:10: fatal error: 
      'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/sysGL.dir/SysGL/Graphics/NativeTextureGL.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/sysGL.dir/all] Error 2
make: *** [all] Error 2
blank-MBP:daedalus username$

**Comment by wally4000** [comment]
you need libpng from homebrew. Works fine on Macs otherwise :)
