### ISSUE TITLE
downloading the file

### ISSUE THREAD

**Issue by brunoman4006** [DaedalusX64/daedalus#29]
i cant download it because my wifi arent fast, so i want to search another way to download it because if i download from the github, in the 43% github blocks the download

is there another way to download DaedalusX64_1_1_8.zip?

**Comment by wally4000** [comment]
Sorry, nothing we can help with. :)

**Comment by rdx-f** [comment]
You can use
https://archive.org/details/daedalus-x-64.7z
May be work
