### ISSUE TITLE
[BUG] Controller pak games don't save/

### ISSUE THREAD

**Issue by FireFire273** [DaedalusX64/daedalus#3]
Controller pak games won't save, They do not detect a controller pak even when set to MemPak in global settings, Tested on my PSP 3001

**Comment by FireFire273** [comment]
Yes I'm using 1.1.7

**Comment by z2442** [comment]
Yes we are working this bug. I think it may be a memory allocation issue.

**Comment by Quzetta** [comment]
The bug is still present on 1.1.8.

Psp 2001

**Comment by FireFire273** [comment]
> The bug is still present on 1.1.8.
> 
> Psp 2001

Thanks for telling me, Seems like i'm gonna stick with a older version of this emulator, specifically r1909.

**Comment by wally4000** [comment]
Save has been fixed in preparation for 1.1.9 Thanks
