### ISSUE TITLE
[BUG] Wiki does not appear to be copied over from old repository

### ISSUE THREAD

**Issue by ste2425** [DaedalusX64/daedalus#34]
The wiki from the old repository (https://github.com/z2442/daedalus/wiki) does not seem to have been cloned over.

The link in the readme for this repository references the wiki in this repository for more information.

If the Wiki files resided in repo itself I would happily copy them over and submit a PR but it seems GitHub wikis don't work like that.

**Comment by wally4000** [comment]
Heya,

Thanks for bringing this to our attention, i've created the temporary page required to setup the wiki if you would like to assist with that :) (IT would be much appreciated, the results for the games are mostly out of date.

Feel free to jump on the DaedalusX64 / PSP Homebrew Discord Server to discuss the Wiki if you like
