### ISSUE TITLE
[BUG] No Sound on Linux

### ISSUE THREAD

**Issue by hcsubser** [DaedalusX64/daedalus#37]
Describe the bug
When running Daedalus on Linux no sound is being played.

To Reproduce
Compile on Linux.
Run any game. (I tried Mario Kart 64, Legend of Zelda Ocarina of time)

Expected behavior
Sound to play.

Device:
 - OS: Ubuntu 20.04
 - Daedalus Version: git from master

**Comment by wally4000** [comment]
Not a bug it's a known issue as Daedalus Linux doesn't have a sound plugin yet.
