### ISSUE TITLE
BSOD Screen

### ISSUE THREAD

**Issue by juanroman74454811** [DaedalusX64/daedalus#38]
Describe the bug
BSOD

To Reproduce
Steps to reproduce the behavior: The BSOD is a bug which happened to me, 

Expected behavior
I expected a BSOD, on my PSP, Sooooooooooooooooooooooooooooooooooooooooooooooo In a chance, the BSOD easter egg showed up,

Device:
 - Device: PSP Slim
 - FW:no
 - Daedalus Version idk

Additional context
How did i get a BSOD, 👿

**Comment by wally4000** [comment]
Daedalus has an exception handler built in which causes the blue screen to appear. kthxbai

**Comment by MotoLegacy** [comment]
Hey there,
This is without a doubt the worst issue I've had the displeasure of responding to and instantly closing.

Next time, please do your due diligence to actually provide something of substance aside from "FW: No" and "Version: idk". We aren't omnipotent. We don't know where you obtained the emulator for certain and we cannot know what version you are using.

Furthermore, BSoDs are specific to Windows so I haven't even a fraction of a clue what you're referring to. Whether you hard crash or receive an error message on the XMB or what.

Check the releases page for the latest stable version of the emulator. If you are still having trouble, please create a more coherent and detailed issue on this repository.

Thanks,
Moto

**Comment by juanroman74454811** [comment]
> Hey there, This is without a doubt the worst issue I've had the displeasure of responding to and instantly closing.
> 
> Next time, please do your due diligence to actually provide something of substance aside from "FW: No" and "Version: idk". We aren't omnipotent. We don't know where you obtained the emulator for certain and we cannot know what version you are using.
> 
> Furthermore, BSoDs are specific to Windows so I haven't even a fraction of a clue what you're referring to. Whether you hard crash or receive an error message on the XMB or what.
> 
> Check the releases page for the latest stable version of the emulator. If you are still having trouble, please create a more coherent and detailed issue on this repository.
> 
> Thanks, Moto

Look, its really hard to know what is my FW, pretty much its a CFW, CFW 1.245.69 probably?
