### ISSUE TITLE
Any plans to make this a libretro core?

### ISSUE THREAD

**Issue by bmaupin** [DaedalusX64/daedalus#4]
I love how RetroArch/libretro allows me to access all my emulators from one place. Are there any plans to make this a libretro core? I saw this in the readme:

> with plans to port to Windows, Mac, PS Vita among other platforms.

Making this a libretro core should help with that goal.

> Any project that is ported to work with this API can be made to run on ANY libretro frontend – now and forever. You maintain a single codebase that only deals with the main program, and you then target one single API (libretro) in order to port your program over to multiple platforms at once. A libretro core written in portable C or C++ can run seamlessly on many platforms with very little or no porting effort.

http://docs.libretro.com/development/cores/developing-cores/

Thanks!

**Comment by bielgiroto** [comment]
The project its still active?

**Comment by TheMrIron2** [comment]
I mean yeah this repo is only a few months old and has had 15 commits in 2 months. You tell me?

As for RetroArch, I have no intention on speaking on behalf of the team here but they have mentioned making a cross-platform SDL build before, at least for the GUI and a cross-platform interpreter. I would not rule it out but I don't think it's a priority for them -- Vita support seems to be their next stepping stone before expanding out past that.

**Comment by z2442** [comment]
Active but no plans for libretro
