### ISSUE TITLE
Mario 64 in-game saves

### ISSUE THREAD

**Issue by dantesquivel** [DaedalusX64/daedalus#40]
Hi - I wanted to thank you for a great emulator, but also note that Mario 64 (which is a great example of how well the emulator runs} cannot load in-game saves.

 I realize the Save States offer a work around for this issue, however, will there be support for in-game saves in that format?

I noticed Daedalusx64 does create the save file in the game saves folder, but it's a .sav file. Does the emulator not support that save file?

EDIT: saving is working normally again, I'm trying to re create the issue to see if I can provide better insight of what caused it originally in case it can help others.

**Comment by ParzivalWolfram** [comment]
I'm having the same issue with SM64, both Zelda games, and Star Fox 64. Saves are written out, but aren't loaded properly. I'm using Daedalusx64 from psp-place, labeled "Built July 17, 2022 (UNKNOWN PSP)" on a PSP 3000 series.

**Comment by wally4000** [comment]
The 1.1.8 release requires you to make the SaveGames folder, this has been fixed for future releases.
:)
