### ISSUE TITLE
how to compile this source?

### ISSUE THREAD

**Issue by Askmewho** [DaedalusX64/daedalus#6]
where are these files??

i am trying to compile it for linux

Make Error at CMakeLists.txt:154 (add_executable):
  Cannot find source file:

    SysPosix/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:150 (add_library):
  Cannot find source file:

    SysPosix/Debug/DaedalusAssertPosix.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:154 (add_executable):
  No SOURCES given to target: daedalus

CMake Error at CMakeLists.txt:150 (add_library):
  No SOURCES given to target: daedalus.lib

-- Build files have been written to: /home/pi/Desktop/daedalus/daedbuild
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
cp: no se puede efectuar `stat' sobre 'daedalus': No existe el fichero o el directorio

**Comment by z2442** [comment]
To compile the linux source you use the .sh included with this repo. 

ex: build_daedalus.sh LINUX_RELEASE

**Comment by Askmewho** [comment]
```
pi@raspberrypi:~/Desktop/daedalus $ ./build_daedalus.sh LINUX_RELEASE
Removing previous build attempt
rm: no se puede borrar '/home/pi/Desktop/daedalus/DaedalusX64/EBOOT.PBP': No existe el fichero o el directorio
mkdir: no se puede crear el directorio «/home/pi/Desktop/daedalus/daedbuild»: El fichero ya existe
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Linux Release Build..
-- Configuring done
CMake Error at CMakeLists.txt:154 (add_executable):
  Cannot find source file:

    SysPosix/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:150 (add_library):
  Cannot find source file:

    SysPosix/Debug/DaedalusAssertPosix.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:154 (add_executable):
  No SOURCES given to target: daedalus


CMake Error at CMakeLists.txt:150 (add_library):
  No SOURCES given to target: daedalus.lib


-- Build files have been written to: /home/pi/Desktop/daedalus/daedbuild
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
cp: no se puede efectuar `stat' sobre 'daedalus': No existe el fichero o el directorio
```

**Comment by z2442** [comment]
The Linux build is still in a unusable state and does not yet support arm cpus.
