### ISSUE TITLE
[BUG] Daedalusx64 freezing on startup in adrenaline

### ISSUE THREAD

**Issue by orangelampshade** [DaedalusX64/daedalus#8]
Describe the bug
Daedalusx64 1.1.8 and 1.1.7 freeze on black screen when booting in adrenaline. Cannot get out of freeze, adrenaline must be force quit. 

To Reproduce
Attempt to load either of the two versions in adrenaline

Expected behavior
Upon selecting either version to boot, psp splash screen is displayed, before emulator freezes on black screen. 

Screenshots
Would just be a black screen. 

Device:
 - Device: Vita Fat
 - FW: 3.65 with enso
 - Daedalus Version: 1.1.7 and 1.1.8

Additional context:

**Comment by Invictaz** [comment]
Disable Gta native resolution patch. Press select and up in Adrenaline XMB. Go to recovery menu. Select plugins. Press X to disable them.

**Comment by orangelampshade** [comment]
Awesome, that worked. Thank you!

**Comment by bielgiroto** [comment]
Should close this one

We have an dedicated daedalus emulator for the Vita already, there's no need to use the PSP version anymore

**Comment by orangelampshade** [comment]
Does the dedicated version have any improvements over the adrenaline based version?

**Comment by bielgiroto** [comment]
Better speed and more frequent updates seems good enough for you?

**Comment by orangelampshade** [comment]
Woah, bit heavy on the sarcasm there, pal. I didn’t know questions were forbidden... 

Sorry for having an interest. Thanks

**Comment by wally4000** [comment]
Yeah I would suggest using the Vita build if possible, the PSP build will post a warning in 1.1.9 :)
