### ISSUE TITLE
[BUG] PPSSPP Crashing When starting DaedalusX64

### ISSUE THREAD

**Issue by Wave3prime15** [DaedalusX64/daedalus#82]
Describe the bug: When i boot DaedalusX64 up in ppsspp it goes to a black screen about 3-4 seconds in and it closes out the PPSSPP Executable. Is there any fix to it?

Device:
 - Device: PSP 2000/3000
 - FW: The Latest
 - Daedalus Version: 1.1.8

**Comment by wally4000** [comment]
Thank you for logging an issue but unfortunately PPSSPP is not supported by DaedalusX64 at this point in time.

We know what is causing the problem but fixing it will require a special build for PPSSPP.

**Comment by Wave3prime15** [comment]
O

what build is it

**Comment by dopeyhex** [comment]
For me the last working build was commit [78a2634](https://github.com/DaedalusX64/daedalus/commit/78a2634e0530c17e74d4ee17068d3f0b8d60127e)
All the next commits don't work on either PSP3000 or PPSSPP

**Comment by Wave3prime15** [comment]
i clicked the link and i see code

now what

**Comment by wally4000** [comment]
I'm sorry but this is not a mechanism for support and is a bug reporting system. Please ask elsewhere.

**Comment by Wave3prime15** [comment]
k
