### ISSUE TITLE
32/16color mode on psp

### ISSUE THREAD

**Issue by CornN64** [DaedalusX64/daedalus#9]
Cool to see that coding for this emu has picked up again :)
I'll need to give this newer version a spin.
One thing I wanted to note (since I did not see it in the readme) is that on the PSP I made it possible  (or at least was) possible to run it in 32bit color mode if the (o) button was held down during boot of the emu.
This gave somewhat less banding (noticeable especially in TV mode if I remember correctly) at the expense of less available VRAM for textures (which was mostly an issue on the PHAT PSP).
Cheers

EDIT:
I gave it a spin and I noticed that async audio finally works without crashing :)
However for some reason the HLE patching vectors does not seem to get stored the first time around with the result that the HLE search happened every time I started a ROM.

**Comment by wally4000** [comment]
Oi, come to our discord, we could use your help ;)

**Comment by wally4000** [comment]
So yeah it should still work with 32 bit color mode :D

**Comment by re4thewin** [comment]
tv out forces 32bit color also here https://discord.gg/WbDSJhU get in here and help these boys out lol
